config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root :to => "home#index", :as => "authenticated_root"
  end

  root :to => 'welcome#index'

  devise_for :users,
             :controllers => { registrations: 'registrations' }

  resources :users

  resources :auctions do
    resources :bids
    resources :pictures
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base

  has_many :bids
  has_many :pictures
  belongs_to :user

  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 1 }


  def refresh
    # the current top price for an auction is the first possible bid that
    # overbids that second highest max_bid, unless there is only one bid
    # in which case the current top price does not change and the user to
    # bid first is still the current winner.
    if !is_first_bid?
      update_price
    end
    # as per requirements, auctions must be extended by 15 mins if a bid
    # is made within the last 5 mins of an auction
    if less_mins_remaining_than? 5
      extend_duration_by_mins 15
    end
    self.save
  end

  def update_price
    ordered_bids = bids.sort_by{ |b| b.max_bid }.reverse
    highest_bid = ordered_bids.shift # also removes highest_bid from ordered_bids
    second_highest_bid = ordered_bids.first
    # increment second highest max_bid by 1 if two highest bids aren't equal
    if highest_bid.max_bid!=second_highest_bid.max_bid
      self.price = second_highest_bid.max_bid + 1
    else #
      self.price = second_highest_bid.max_bid
    end
  end

  def self.search(query)
    where("title like ? OR description like ?", "%#{query}%", "%#{query}%")
  end

  def extend_duration_by_mins mins
    self.duration += mins
  end

  def has_no_bids?
    self.bids.empty?
  end

  def is_first_bid?
    self.bids.count <= 1
  end

  def less_mins_remaining_than? n
    (((self.created_at + self.duration*60) - Time.now) - (n*60)) < 0
  end

  def time_remaining
    (self.created_at + self.duration*60) - Time.now
  end

  def running?
    self.time_remaining>0
  end

  def tweets
    options = {count: 6, result_type: 'recent'}
    $twitter.search(self.title, options).take(6) #somehow the count argument doesn't work...
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  require 'google-search'

  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter  :owns_auction!, :only => [:update, :edit, :destroy]

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.user = current_user

    if @auction.save
      redirect_to @auction
    else
      render 'new'
    end
  end

  def index
    running_auctions = Array.new
    closed_auctions = Array.new
    if params[:search]
      auctions = Auction.search(params[:search]).sort{|a,b|
        a.time_remaining <=> b.time_remaining }
    else
      auctions = Auction.all.sort{|a,b|
        a.time_remaining <=> b.time_remaining }
    end
    auctions.each do |a|
      if a.running?
        running_auctions.push(a)
      else
        closed_auctions.push(a)
      end
    end
    running_auctions.sort{|a,b|
      a.time_remaining  <=> b.time_remaining}
    closed_auctions.sort{|a,b|
      a.time_remaining  <=> b.time_remaining}.reverse
    @auctions = running_auctions.concat closed_auctions

  end

  def show
    @auction = Auction.find(params[:id])
    @bids = @auction.bids.sort_by{ |b| [-b.max_bid, b.created_at] } #sorts bid by max_bid DESC, created_at ASC
    @bidder = (@bids.first.nil? ? nil : @bids.first.user)
    # Fetch images from google
    @google_images = find_google_images(@auction.title)
    @user_pictures =  @auction.pictures
    @tweets = @auction.tweets
  end

  def update
    @auction = Auction.find(params[:id])

    if @auction.update(auction_params)
      redirect_to @auction
    else
      render 'edit'
    end
  end

  def edit
    @auction = Auction.find(params[:id])
  end

  def destroy
    @auction = Auction.find(params[:id])
    unless @auction.bids.empty?
      flash[:error] = 'Auction already has bids, cannot be deleted!'
      redirect_to @auction
    end
    @auction.destroy
    redirect_to auctions_path
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :description, :price, :duration)
  end

  def find_google_images(name)
    @images = Array.new
    Google::Search::Image.new(:query => name).first(5).each do |image|
      @images.push image
    end
    @images
  end

end

app/helpers/auctions_helper.rb
module AuctionsHelper
  # formats a duration in seconds to hh:mm:ss
  def format_duration seconds
    Time.at(seconds).utc.strftime("%H:%M:%S")
  end

  def format_duration_if_pos seconds
    if seconds > 0
      format_duration(seconds)
    else
      "closed"
    end
  end

end

app/views/auctions/_form.html.erb
<%= form_for @auction do |f| %>
    <% if @auction.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@auction.errors.count, "error") %> prohibited
                this auction from being published:</h2>
            <ul>
                <% @auction.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.label :price %><br>
        <%= f.text_field :price %>
    </p>
    <p>
        <%= f.label :duration %><br>
        <%= f.number_field(:duration, :required => true, :min => 5) %>
    </p>
    <p>
        <%= f.submit %>
    </p>
 <% end %>

app/views/auctions/_tweet.html.erb
<p>
    > <%= tweet.text %> <br>
    <small><%=  fa_icon "twitter" %> <%= time_ago_in_words(tweet.created_at) %> ago by @<%= tweet.user.username %></small>
</p>

app/views/auctions/edit.html.erb
<h1>Edit auction</h1>

<%= form_for @auction do |f| %>
    <% if @auction.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@auction.errors.count, "error") %> prohibited
                this auction from being published:</h2>
            <ul>
                <% @auction.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/auctions/index.html.erb
<h1><%= fa_icon "list-ul" %> Auctions</h1>

<%= form_tag auctions_path, method: :get do %>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon hidden-xs"><%= fa_icon "search" %></span>
                <%= text_field_tag :search, params[:search], placeholder: "Search Auctions", class: "form-control" %>
                    <span class="input-group-btn">
                <%= submit_tag "Search", :name => nil, class: "btn btn-info" %>
            </span>
        </div>
    </div>
<% end %>

<table class="table table-bordered table-striped table-responsive">
    <thead>
    <tr>
        <th><%= fa_icon "car" %><span class="hidden-xs"> Car type</span></th>
        <th><%= fa_icon "user" %><span class="hidden-xs"> Seller</span></th>
        <th><%= fa_icon "clock-o" %><span class="hidden-xs"> Time Remaining</span></th>
        <th><%= fa_icon "gavel" %><span class="hidden-xs"> Highest bid</span></th>
    </tr>
    </thead>
    <tbody>
    <% @auctions.each do |auction| %>
        <tr>
            <td>
                <div style="float: left; width: auto;">
                    <strong class="hidden-xs"><%= link_to auction.title, auction_path(auction) %>&nbsp;</strong>
                    <strong class="visible-xs"><%= link_to (auction.title.length > 20 ? auction.title[0,20]+"..." : auction.title), auction_path(auction) %>&nbsp;</strong>
                </div>
                <div style="float: left; width: auto;">
                    <%= if auction.user == current_user then button_to 'Edit', edit_auction_path(auction), :method => "get", class: "btn btn-warning btn-xs" end %>
                </div><div style="float: left; width: 2px;"><p>&nbsp;</p>
            </div>
                <div style="float: left; width: auto;">
                    <%= if (auction.user == current_user and auction.bids.first.nil?) then button_to 'Delete', auction_path(auction), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" end %>
                </div>
            </td>
            <td><%= if auction.user == current_user then "you" else auction.user.username end %></td>
            <script>
                jQuery(document).ready(function() {
                    if(<%= auction.time_remaining > 0 %>) {
                        $('#<%= auction.__id__ %>').countdown('<%= ((Time.now.to_f * 1000) + ((auction.time_remaining * 1000))).to_i %>')
                                .on('update.countdown', function (event) {
                                    var $this = $(this).html(event.strftime(''
                                            + '<span>%d</span>:'
                                            + '<span>%H</span>:'
                                            + '<span>%M</span>:'
                                            + '<span>%S</span>'))
                                });
                    }
                    else {
                        $('#<%= auction.__id__ %>').html("closed");
                    }
                });
            </script>
            <td id="<%= auction.__id__ %>" class="text-right"></td>
            <td class="text-right"><%= number_with_delimiter(auction.price.round, delimiter: "'") %> CHF</td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= button_to "New auction", new_auction_path, :method => "get", class: "btn btn-success" %>

app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

app/views/auctions/show.html.erb
<script>
    jQuery(document).ready(function() {
        if(<%= @auction.time_remaining > 0 %>) {
            $('#clock').countdown('<%= ((Time.now.to_f * 1000) + ((@auction.time_remaining * 1000))).to_i %>')
                .on('update.countdown', function (event) {
                    var $this = $(this).html(event.strftime(''
                        + '<span>%d</span>:'
                        + '<span>%H</span>:'
                        + '<span>%M</span>:'
                        + '<span>%S</span>'))
                })
                .on('finish.countdown', function (event) {
                    location.reload(true);
                });
        }
        else {
            $('#clock').html("Auction closed.");
        }
    });
</script>

<div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
    <h1><%= fa_icon "car" %> <%= @auction.title %></h1>
    <hr>
    <h2><strong><%= fa_icon "clock-o" %> <span id="clock"></span></strong></h2>

    <p>Time remaining</p>
    <hr>


    <div class="visible-xs">
        <h2>
            <%= fa_icon "gavel" %> <strong><%= number_with_delimiter(@auction.price.round, delimiter: "'") %> CHF</strong>
        </h2>
        <p>
            <%= @auction.running? ? (@auction.bids.empty? ? "Starting" : "Current") : "Final"  %> bid
            <%= @bidder.nil? ? '' : ('by '+ (@bidder.eql?(current_user) ? "you" : @bidder.username)) %>
        </p>
        <hr>
        <% unless is_own_auction? or !@auction.running? %>
            <%= render "bids/form" %>
        <% end %>
        <% if is_own_auction? %>
            <div style="float: right; width: auto;">
                <%= if (is_own_auction? and @auction.bids.first.nil?) then button_to 'Delete', auction_path(@auction), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" end %>
            </div>
            <div style="float: right; width: auto;">
                <p>&nbsp;</p>
            </div>
            <div style="float: right; width: auto;">
                <%= if is_own_auction? then button_to 'Edit', edit_auction_path(@auction), :method => "get", class: "btn btn-warning" end %>
            </div>
        <% end %>
        <br>
        <br>
        <hr>
    </div>

    <p>
        <strong>Seller:</strong>
        <%= if @auction.user == @current_user then "you" else @auction.user.username end %>
    </p>
    <p>
        <strong>Description:</strong></p>
    <p>
        <%= @auction.description %>
    </p>
    <p><strong>Google Pictures:</strong></p>
    <p><% @google_images.each do |image| %>
        <%= image_tag image.thumbnail_uri, size: "#{image.thumbnail_width}x#{image.thumbnail_height}" %>
    <% end %>
    </p>
    <% if !@user_pictures.empty? then %>
        <p><strong>Users Pictures:</strong></p>
    <% end %>

    <p><% @user_pictures.each do |picture| %>
            <% if is_own_auction? %>
                <%= link_to image_tag(picture.url, class: 'pseudo-thumbnail'), auction_picture_path(@auction, picture) %>
            <% else %>
               <%= image_tag picture.url , class: 'pseudo-thumbnail'%>
            <% end %>
        <% end %>
    </p>
    <% if is_own_auction?%>
        <p>
            <%= render "pictures/form" %>
        </p>
    <% end %>

    <p><strong>Related tweets:</strong></p>
    <%= render partial: 'tweet', collection: @tweets %>
    <hr>
</div>

<div class="col-lg-3 col-md-3 col-sm-4 hidden-xs text-right">
    <h1><%= fa_icon "gavel" %></h1>
    <hr>
    <h2>
        <strong><%= number_with_delimiter(@auction.price.round, delimiter: "'") %> CHF</strong>
    </h2>
    <p>
        <%= @auction.running? ? (@auction.bids.empty? ? "Starting" : "Current") : "Final"  %> bid
        <%= @bidder.nil? ? '' : ('by '+ (@bidder.eql?(current_user) ? "you" : @bidder.username)) %>
    </p>
    <hr>
    <% unless is_own_auction? or !@auction.running? %>
        <%= render "bids/form" %>
    <% end %>
    <% if is_own_auction? %>
        <div style="float: right; width: auto;">
            <%= if (is_own_auction? and @auction.bids.first.nil?) then button_to 'Delete', auction_path(@auction), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" end %>
        </div>
        <div style="float: right; width: auto;">
            <p>&nbsp;</p>
        </div>
        <div style="float: right; width: auto;">
            <%= if is_own_auction? then button_to 'Edit', edit_auction_path(@auction), :method => "get", class: "btn btn-warning" end %>
        </div>
    <% end %>
</div>