config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root :to => "home#index", :as => "authenticated_root"
  end

  root :to => 'welcome#index'

  devise_for :users,
             :controllers => { registrations: 'registrations' }

  resources :users

  resources :auctions do
    resources :bids
    resources :pictures
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>AUTOTRADE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="/"><%= fa_icon "car" %> <strong>AUTOTRADE</strong></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to root_path do %>
                        <%= fa_icon "home" %> Home
                    <% end %>
                <li>
                    <%= link_to auctions_path do %>
                        <%= fa_icon "list-ul" %> Auctions
                    <% end %>
                </li>
            </ul>
            <% if current_user %>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to edit_user_registration_path do %>
                            <%= fa_icon "wrench" %> Profile
                        <% end %>
                    </li>
                    <li><%= link_to destroy_user_session_path, :method => :delete do %>
                            <%= fa_icon "sign-out" %> Sign Out
                        <% end %>
                    </li>

                </ul>
            <% end %>

        </div><!--/.nav-collapse -->

    </div>
</div>

<div class="container">

    <%= yield %>

    <div class="container" style="display: block"><br><br></div>
</div>
</body>
</html>